### PR TITLE
Upgrades AWS sdk to v3

### PR DESCRIPTION
**Pull request by fabiokr**

### CODE REVIEW

**Review by rubemz — APPROVED** [review]

**Review by boone — COMMENTED** [review]
Nice!

**Comment by rubemz** [comment]
@fabiokr before merging this one, could you run a outatime command to download a versioned repo and make sure it works?

**Comment by fabiokr** [comment]
@rubemz Tested it, working fine.

**Review by rubemz — APPROVED** [review]

**Comment by boone** [comment]
@fabiokr can you rebase?

**Comment by fabiokr** [comment]
@boone We can't merge this yet because of our dependency on paperclip and aws v2, will do once that one is good.

**Comment by boone** [comment]
@fabiokr I think we can merge it because our Gemfile dependencies specify "~> 0.3.0" and this is version "0.4.0". Should be OK, right?

**Comment by boone** [comment]
@fabiokr any thoughts on my last comment? I think we could merge this and not affect our dependent apps.

**Comment by fabiokr** [comment]
@boone Makes sense.

**Review by boone — APPROVED** [review]

**Pull request merged**
